name: ci-code-tech

on:
  push:
    branches:
      - main

jobs:
  check-application:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Node Setup
          uses: actions/setup-node@v4
          with:
            node-version: 16

        - name: Install dependencies
          run: yarn

        - name: Unit Tests
          run: yarn test

  